language: python

python:
  - "3.6"
  # - "3.7"

# env:
#   global:
#     - CXX=g++-4.8
#     - DISPLAY=:99.0
#     - CHROME_BIN=/usr/bin/google-chrome
addons:
   apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD/geckodriver
  - sudo mv chromedriver_linux64/chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# before_script:
#    - "sh -e /etc/init.d/xvfb start"
#    - sleep 3 #wait a while before xvfb to start
script:
  - tox
  - coverage run -m pytest
  - behave
  - coverage report -m
# after_script:
#   - "sh -e /etc/init.d/xvfb stop"
after_success:
  coveralls
